#pragma once
#include <iostream>
#include <ctime>
#include "MainMenu.h"

using namespace std;

int randomnum() {
	srand((unsigned int)time(NULL));
	int random = (rand() % 69) + 10;
	return random;
}

void LogoSplash() {
		cout << "                  AAAA                                      AAAAAA                                                                              AAAAAAAAAAA                                                                               AAAAAAAAA                                   " << endl;Sleep(randomnum());
		cout << "               AAAAAAAAAA                                AAAAAAAAAAAAA                     AAAAAAAAAAAAAAAAAAAAAAAAA                         AAAAAAAAAAAAAAAAAA             AAAAAAAAAAAAA                         AAAAAAAAAAAAAAA         AAAAAAAAA                                   " << endl;Sleep(randomnum());
		cout << "               AAAAAAAAAA                                AAAAAAAAAAAAA                    AAAAAAAAAAAAAAAAAAAAAAAAAAAA                    AAAAAAAAAAAAAAAAAAAAAAA          AAAAAAAAAAAAAAAA                      AAAAAAAAAAAAAAAA         AAAAAAAA                                    " << endl;Sleep(randomnum());
		cout << "               AAAAAAAAAA                              AAAAAAAAAAAAAAAA                   AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA               AAAAAAAAAAAAAAAAAAAAAAAAA         AAAAAAAAAAAAAAAAAA                    AAAAAAAAAAAAAAAAA         AAAAAAAAV                                   " << endl;Sleep(randomnum());
		cout << "              AAAAAAAAAAA                              AAAAAAAAAAAAAAAA                   AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA            AAAAAAAAAAAAAAAAAAAAAAAAA          AAAAAAAAAAAAAAAAAA                  YAAAAAAAAAAAAAAAAA          AAAAAAAA                                    " << endl;Sleep(randomnum());
		cout << "              AAAAAAAAAA                             AAAAAAAAAAAAAAAAAA                  AAAAAAAAAA           AAAAAAAAAAAAAA          AAAAAAAAAAA           AAAA          AAAAAAAAAAAAAAAAAA                 AAAAAAAAAAAAAAAAAAA          AAAAAAAA                                    " << endl;Sleep(randomnum());
		cout << "             AAAAAAAAAAA                            AAAAAAAAAAAAAAAAAAAA                 AAAAAAAAA               AAAAAAAAAAAA        AAAAAAAAAAA                          AAAAAAAAAAAAAAAAAA                AAAAAAAAAAAAAAAAAAAW         AAAAAAAA                                     " << endl;Sleep(randomnum());
		cout << "              AAAAAAAAA                            AAAAAAAAA   AAAAAAAAA                AAAAAAAAAA                AAAAAAAAAAA        AAAAAAAAAA                          AAAAAAAAAAAAAAAAAAA               AAAAAAAAAA AAAAAAAAA          AAAAAAA              AAAAAAAAAAAAA           " << endl;Sleep(randomnum());
		cout << "             AAAAAAAAAA                           AAAAAAAAAA   AAAAAAAAA                AAAAAAAAAA                 AAAAAAAAAAA       AAAAAAAAAA                          AAAAAAAAA AAAAAAAAAA             AAAAAAAAAM  AAAAAAAAA          AAAAAAA          AAAAAAAAAAAAAAAAAAAA        " << endl;Sleep(randomnum());
		cout << "             AAAAAAAAA                           AAAAAAAAAA    AAAAAAAAAA              AAAAAAAAAAA                 AAAAAAAAAAA       AAAAAAAAAAA                        AAAAAAAAAA  AAAAAAAAA             AAAAAAAAA  AAAAAAAAAA           AAAA          UAAAAAAAAAAAAAAAAAAAAA        " << endl;Sleep(randomnum());
		cout << "            AAAAAAAAAA                          AAAAAAAAAA     AAAAAAAAAA              AAAAAAAAAAA                 AAAAAAAAAAA       AAAAAAAAAAAAAA                     AAAAAAAAAA  AAAAAAAAA           AAAAAAAAAA   AAAAAAAAAA                        AAAAAAAAAAAAAAAAAAAAAA         " << endl;Sleep(randomnum());
		cout << "            AAAAAAAAAA                          AAAAAAAAA       AAAAAAAAA              AAAAAAAAAA                  AAAAAAAAAAA        AAAAAAAAAAAAAAAA                 AAAAAAAAAA   AAAAAAAAA          AAAAAAAAAA   AAAAAAAAAA                         AAAAAAAAA          AA          " << endl;Sleep(randomnum());
		cout << "           AAAAAAAAAAA                        AAAAAAAAAA        AAAAAAAAA             AAAAAAAAAAA                  AAAAAAAAAAA         AAAAAAAAAAAAAAAAAA               AAAAAAAAA    AAAAAAAAA        AAAAAAAAAA    AAAAAAAAAA                        AAAAAAAAA                       " << endl;Sleep(randomnum());
		cout << "           AAAAAAAAAA                         AAAAAAAAA         AAAAAAAAA             AAAAAAAAAA                    AAAAAAAAA           AAAAAAAAAAAAAAAAAAA            AAAAAAAAA     AAAAAAAAAA      AAAAAAAAAA    AAAAAAAAAA                         AAAAAAAAAA                      " << endl;Sleep(randomnum());
		cout << "          AAAAAAAAAAA                       AAAAAAAAAA           AAAAAAAAA            AAAAAAAAAA                   AAAAAAAAAA              AAAAAAAAAAAAAAAAA           AAAAAAAAA     AAAAAAAAAA     AAAAAAAAAA      AAAAAAAAA                         AAAAAAAAAAAA                    " << endl;Sleep(randomnum());
		cout << "          AAAAAAAAAA                       AAAAAAAAAAA           AAAAAAAAA           AAAAAAAAAAA                  AAAAAAAAAA                  AAAAAAAAAAAAAAA         AAAAAAAAAA      AAAAAAAAA    AAAAAAAAAA      AAAAAAAAA                           AAAAAAAAAAAAAAAA               " << endl;Sleep(randomnum());
		cout << "          AAAAAAAAAA                      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA           AAAAAAAAAAA                 AAAAAAAAAAA                     AAAAAAAAAAAAA        AAAAAAAAA       AAAAAAAAA   AAAAAAAAAA       AAAAAAAAA                            AAAAAAAAAAAAAAAAA             " << endl;Sleep(randomnum());
		cout << "          AAAAAAAAA                      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA          AAAAAAAAAA                 AAAAAAAAAAAA                       AAAAAAAAAAA       AAAAAAAAAA       AAAAAAAAAA AAAAAAAAA        AAAAAAAAAA                              AAAAAAAAAAAAAAAA            " << endl;Sleep(randomnum());
		cout << "         AAAAAAAAAA                     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA         AAAAAAAAAAA                AAAAAAAAAAAA                        AAAAAAAAAAA       AAAAAAAAA         AAAAAAAA AAAAAAAAAA        AAAAAAAAAA                                 AAAAAAAAAAAAAA           " << endl;Sleep(randomnum());
		cout << "         AAAAAAAAAA                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA         AAAAAAAAAA               AAAAAAAAAAAA                          AAAAAAAAAAA      AAAAAAAAAA         AAAAAAAAAAAAAAAAAA        AAAAAAAAAA                                     AAAAAAAAAAAA          " << endl;Sleep(randomnum());
		cout << "        AAAAAAAAAAA                   AAAAAAAAAAA                AAAAAAAAAAA        AAAAAAAAAA             AAAAAAAAAAAAAAAAAAAAAAA                AAAAAAAAAAA       AAAAAAAAA          AAAAAAAAAAAAAAAA          AAAAAAAAA                                       AAAAAAAAAAA          " << endl;Sleep(randomnum());
		cout << "        AAAAAAAAAAA                  AAAAAAAAAAA                  AAAAAAAAAA       AAAAAAAAAA           AAAAAAAAAAAAAAAAAAAAAAAAAAAA            AAAAAAAAAAAAAAAAAAAAAAAAAAAAA          AAAAAAAAAAAAAAA          AAAAAAAAAA                         AA            AAAAAAAAAA           " << endl;Sleep(randomnum());
		cout << "       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                   AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA           AAAAAAAAAAAAAAA          AAAAAAAAA                         AAAAAAA     AAAAAAAAAAAA            " << endl;Sleep(randomnum());
		cout << "       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA          AAAAAAAAAAAAAA           AAAAAAAAA                        WAAAAAAAAAAAAAAAAAAAAAAA             " << endl;Sleep(randomnum());
		cout << "       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA            AAAAAAAAAAA             AAAAAAAA                         AAAAAAAAAAAAAAAAAAAAAAA              " << endl;Sleep(randomnum());
		cout << "       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA            AAAAAAAAAAA            AAAAAAAAAA                         AAAAAAAAAAAAAAAAAAA                 " << endl;Sleep(randomnum());
		cout << "                                                                                                                                                                                                                                                                                      " << endl;Sleep(randomnum());
		cout << "            AAAAAAAAAAAAAAA                AAAAAAAAA              AAAAAAAAAA                AAAAAAAAA        AAAAAAAAAAAAAAAAAAAAAAAAAAA           AAAAAAA            AAAAAT          AAAAAAAAAAAAAA            AAAAAAAAAAAAAAAA            AAAAAAA       AAAAAAAA       AAAAAAAAAAAA " << endl;Sleep(randomnum());
		cout << "         AAAAAAAAAAAAAAAAAAAA             AAAAAAAAAA             AAAAAAAAAAA              AAAAAAAAAAAA     AAAAAAAAAAAAAAAAAAAAAAAAAAAAA           AAAAAAA           AAAAAAA        AAAAAAAAAAAAAAAAAA          AAAAAAAAAAAAAAAAAA         AAAAAAAA       AAAAAAAA    AAAAAAAAAAAAAAAA" << endl;Sleep(randomnum());
		cout << "      AAAAAAAAAAAAAAAAAAAAAAA            AAAAAAAAAAA            AAAAAAAAAAAA             YAAAAAAAAAAA      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA         AAAAAAAAA         AAAAAAA      AAAAAAAAAAAAAAAAAAAAAAA        AAAAAAAAAAAAAAAAAAAA       AAAAAAA     AAAAAAAAA     AAAAAAAAAAAAAAAAA" << endl;Sleep(randomnum());
		cout << "    AAAAAAAAAAA        A AAAA           AAAAAAAAAAAAA           AAAAAA AAAAA            AAAAAAAAAAAAA      AAAAAAA                AAAAAAA       AAAAAAAAAAA        IAAAAAP     AAAAAAAAAA       AAAAAAAA       AAAAAAA      AAAAAAAA      AAAAAAAR    AAAAAAAAA    AAAAAAAAA          " << endl;Sleep(randomnum());
		cout << "   AAAAAAAAA                           AAAAAAAAAAAAAA           AAAAAA AAAAAA          AAAAAA AAAAAA      AAAAAAA                 AAAAAAA       AAAAAAAAAAA        AAAAAA     AAAAAAAA           AAAAAAAA      AAAAAAA       AAAAAAA      AAAAAAA    AAAAAAAA       AAAAAA            " << endl;Sleep(randomnum());
		cout << "  AAAAAAA                             AAAAAAA  AAAAAA          AAAAAAA AAAAAA         AAAAAA AAAAAAA      AAAAAAA                 AAAAAAA      AAAAAAAAAAAA       AAAAAAA    AAAAAAA              AAAAAAA     AAAAAAA        AAAAAAA      AAAAAAA  AAAAAAAK        AAAAAAAA           " << endl;Sleep(randomnum());
		cout << " AAAAAAAA                            AAAAAAA   AAAAAAA         AAAAAAA AAAAAAA      AAAAAAAA AAAAAA       AAAAAA                  AAAAAAA     AAAAAA AAAAAA      AAAAAA      AAAAAA     AAAAAA    AAAAAAA     AAAAAAA       AAAAAAAA     AAAAAAAA AAAAAAA          AAAAAAAAA          " << endl;Sleep(randomnum());
		cout << "AAAAAAAA      AAAAAAAAAAAA          AAAAAAE    AAAAAAA         AAAAAAA  AAAAAA      AAAAAA   AAAAAA      AAAAAAAAAAAAAAAAA        AAAAAAA    AAAAAA  AAAAAA     AAAAAA      AAAAAAA    AAAAAAAA   AAAAAAA    AAAAAAAA  YAAAAAAAAAAA      AAAAAAAAAAAAAAA            AAAAAAAAAAA       " << endl;Sleep(randomnum());
		cout << "AAAAAAA      AAAAAAAAAAAAAA        AAAAAAA      AAAAAA        AAAAAAA  AAAAAAA     AAAAAA   AAAAAA       AAAAAAAAAAAAAAAAA        AAAAAAA    AAAAAA  AAAAAA     AAAAAA     AAAAAAAA   AAAAAAAAA  AAAAAAAA    AAAAAAAAAAAAAAAAAAAA        AAAAAAAAAAAAA                AAAAAAAAAAAA    " << endl;Sleep(randomnum());
		cout << "AAAAAAA      AAAAAAAAAAAAAA       AAAAAAA       AAAAAA        AAAAAAA   AAAAAAA  AAAAAAAA   AAAAAAA     AAAAAAAAAAAAAAAAA         AAAAAAA   AAAAAA   AAAAAA   AAAAAAA      AAAAAAA    AAAAAAAAA  AAAAAAA     AAAAAAAAAAAAAAAAA          AAAAAAA AAAAAAAA               AAAAAAAAAAAAA  " << endl;Sleep(randomnum());
		cout << "AAAAAAA             AAAAAA       AAAAAAAAAAAAAAAAAAAAA       AAAAAAA     AAAAAA AAAAAAAA   AAAAAAA      DAAAAAAA                   AAAAAA  AAAAAA    AAAAAAA AAAAAAA       AAAAAAA    AAAAAAAA   AAAAAAO     AAAAAA AAYAAAAAAAA         AAAAAAA AAAAAAAA                  AAAAAAAAAA  " << endl;Sleep(randomnum());
		cout << "AAAAAAA            AAAAAAA      AAAAAAAAAAAAAAAAAAAAAAA      AAAAAAA    UAAAAAA AAAAAA     AAAAAAA      AAAAAAA                    AAAAAA AAAAAA     AAAAAAA AAAAAA       AAAAAAAA             AAAAAAAA     AAAAAAA      AAAAAAA       AAAAAAAA  AAAAAAAA                    AAAAAAA  " << endl;Sleep(randomnum());
		cout << "AAAAAAAA           AAAAAA      AAAAAAAAAAAAAAAAAAAAAAAA      AAAAAA      AAAAAAAAAAAA      AAAAAAA      AAAAAAA                    AAAAAA AAAAAA     AAAAAAAAAAAAAA        AAAAAAAG           AAAAAAAA      AAAAAAA      AAAAAAA       AAAAAAAQ   AAAAAAAA                   AAAAAAA  " << endl;Sleep(randomnum());
		cout << "AAAAAAAAA         AAAAAAA     AAAAAAA            AAAAAA      AAAAAA       AAAAAAAAAA      AAAAAAA      AAAAAAA                     AAAAAAAAAAAA       AAAAAAAAAAA          AAAAAAAA          AAAAAAAA      AAAAAAAP       AAAAAAL      AAAAAAA     AAAAAAAAAAAAAAA           AAAAAAA  " << endl;Sleep(randomnum());
		cout << " AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA            AAAAAAAAAAAAAAAAAA        AAAAAAAAA       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA          AAAAAAAAAAA        AAAAAAAAAAX           AAAAAAAAAAAAAAAAAAAAAAAA       AAAAAAA        AAAAAAA     AAAAAAAA     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA    " << endl;Sleep(randomnum());
		cout << "  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA              AAAAAAAAAAAAAAAAAA       AAAAAAAA        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA          AAAAAAAAAA         AAAAAAAAAA             AAAAAAAAAAAAAAAAAAAAA         AAAAAAA        WAAAAAAAAAAAAAAAAAA        AAAAAAAAAAAAAAAAAAAAAAAAAAAA     " << endl;Sleep(randomnum());
		cout << "     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA              AAAAAAAAAAAAAAAAA        AAAAAAA         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA            AAAAAAAA          AAAAAAAAA                DAAAAAAAAAAAAAA            AAAAAAAA        AAAAAAAAAAAAAAAAAAA         AAAAAAAAAAAAAAAAAAAAAAAAQ       " << endl;Sleep(3000);
		//Almost as large as your mama!
}